# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Metrology Lecture Book
author: Katharina-S. Isleif
logo: i_mt.png
copyright: "2022"  # Copyright year to be placed in the footer

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

exclude_patterns: [archive/*]
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: mtbook.tex
  latex_engine: pdflatex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Kisleif/mtbook  # Online location of your book https://gitlab.com/username/project
  path_to_book: "" # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  use_multitoc_numbering: true
  comments:
    hypothesis: true

launch_buttons:
  notebook_interface: classic
  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  thebe        : true
  #jupyterhub_url: "https://github.com/Kisleif/mtbook"  # The URL for your JupyterHub. (e.g., https://datahub.berkeley.edu)
  colab_url: "https://colab.research.google.com"

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
    - html_image
    
sphinx:
  config:
    language: de
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  extra_extensions:
  - sphinx_proof
  html_context:
    default_mode: light